### ISSUE TITLE
Path error when specifying extras

### ISSUE THREAD

**Issue by cseHdz** [lucidsushi/gs_pip_install#131]
https://github.com/lucidsushi/gs_pip_install/blob/09668ce1fe393dc338b5b3f3181f76bd44891e74/gs_pip_install/gs_pip_install.py#L79

Currently a list of lists is created - will raise:

ERROR: Invalid requirement: 'gcs_packages/geotab_data_factory.tar.gz[[pipelines]]'
Hint: It looks like a path. File 'gcs_packages/geotab_data_factory.tar.gz[[pipelines]]' does not exist.

Replace to `install_path = f"{install_path}{extras[package]}`

**Comment by lucidsushi** [comment]
fixed in https://github.com/lucidsushi/gs_pip_install/tree/v0.2.2
